
  name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Adjust the Node.js version as per your project's requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test:ci -- --coverage --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Update coverage badges
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
        run: |
          npm install -g istanbul-badges
          istanbul-badges shield --input coverage/stslib/coverage-summary.json --exclude none > badges/coverage.svg

