 # this workflow will check that the app runs correctly + ensures all test cases pass. 

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
 

    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test:ci 
    - run: npm i coverage-badges-cli -g
    - run: coverage-badges --output coverage/badges.svg
 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./coverage
       
    - name: Update coverage badges
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        coverage-summary-path: coverage/stslib/coverage-summary.json
        badges-directory: ./badges
        protected-branches: '["master", "develop"]'
