name: Coverage Badge

on:
  push:
    branches:
      - coverage-workflow  # Trigger workflow on push to coverage workflow branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests targeting main branch

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm test -- --coverage --coverageReporters=text-summary  # Adjust this command if needed

    - name: Install coverage-badges-cli
      run: npm install -g coverage-badges-cli

    - name: Generate coverage badge
      run: |
        # Extract coverage percentage from the text-summary report
        COVERAGE=$(grep -oP 'All files\s+\K[0-9]+(?=%)' coverage/coverage-summary.json)
        if [ -z "$COVERAGE" ]; then
          COVERAGE=0
        fi
        # Generate badge
        coverage-badges --coverage $COVERAGE --color green --label "Coverage" > coverage-badge.svg

    - name: Commit and push badge
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "GitHub Actions"
        author_email: "actions@github.com"
        message: "Update coverage badge"
        add: "coverage-badge.svg"
